Vidly2/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly2.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Vidly2/Controllers/SendMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly2.Models;
using Vidly2.Helper;
using System.Data.Entity;

namespace Vidly2.Controllers
{
    public class SendMailController : Controller
    {
        private ApplicationDbContext _context;

        public SendMailController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: SendMail
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendEmailView()
        {
            var test = new SendMail();
            test.EmailSubject = MailHelper.SendMail1();

            return View(test);
        }

        public ActionResult SendEmailView2(SendMail sendMail)
        {
            var test = new SendMail();
            test.EmailSubject = MailHelper.SendMail2(sendMail);

            return View(test);
        }

        public ActionResult SendEmailView3()
        {
            var customer = _context.Customers.Include(c => c.MembershipType).ToList();
            var test = new Customer();
            string test2 = "";
            string test3 = "nurfazianas@gmail.com";

            foreach (var test1 in customer)
            {
                test2 = test2 + test1.Name + ",";
            }

            test2 = test2.Remove(test2.Length - 1);
            test.Name = MailHelper.SendMail3(test2, test3);

            return View(test);

        }
    }
}

Vidly2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Your Online Video Rental Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly2/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                <li>@Html.ActionLink("Email", "Index", "SendMail")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>